#This is REF3 using hg19 instead
#See Makefile for hg19 source in /Data/resources
#See samtools view -H for bam files to know which reference was used in alignment  
REF_SAMPLES: ['UM14-1_P26_150115','UM4-6_P15_150116','WA09_P25_140528','WA14_P21_131206','WA17_P12_140530','WA18_P9_140530','WA19_P11_140529','WA26_P15_140606','WA27_P15_140613','WIBR2_P33_140617','WIBR6_P11_140617'] 

COHORT: "TIER1_WGS_REF3"
REF_VCF: "TIER1_WGS_REF3.vcf"

GENOME: "/Data/resources/Homo_sapiens_assembly19"
SRC : "/Data/pipeline/src"

CHROMOSOMES: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11','chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20' , 'chr21', 'chr22', 'chrX', 'chrY', 'chrM'] 

